# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: clang
      language: cpp
      sudo: required
      dist: precise
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=precise_clang
        - DETAILS="debug build, no libtool"
    - os: linux
      compiler: clang
      language: cpp
      sudo: required
      dist: trusty
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=trusty_clang
        - DETAILS="optimized build, no libtool"
    - os: linux
      compiler: clang
      language: cpp
      sudo: required
      dist: precise
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=mingw
        - DETAILS="debug build, libtool"
    - os: linux
      compiler: clang
      language: cpp
      sudo: required
      dist: precise
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=mingw_w64
        - DETAILS="optimized build, libtool"
    - os: linux
      compiler: gcc
      language: cpp
      sudo: required
      dist: precise
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=python3
        - DETAILS=""
    - os: linux
      compiler: gcc
      language: cpp
      sudo: false
      dist: trusty
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      apt:
        packages:
          - ccache
      env:
        - BUILD_NAME=android
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - sourceline: "ppa:openjdk-r/ppa"
            - sourceline: "ppa:ubuntugis/ubuntugis-unstable"
            - sourceline: "ppa:miurahr/gta"
          packages:
            - clang-4.0
            - openjdk-8-jdk
          env:
            - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      language: cpp
      compiler: clang
      sudo: required
      dist: trusty
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=cmake
        - DETAILS="Build with cmake and clang-4 on trusty"
    - os: linux
      compiler: gcc
      language: cpp
      sudo: false
      dist: precise
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      apt:
        packages:
          - ccache
      env:
        - BUILD_NAME=big_endian
        - DETAILS=""
    - os: linux
      compiler: gcc
      language: cpp
      sudo: required
      dist: precise
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=gcc48_stdcpp11
        - DETAILS=""
    - os: linux
      compiler: gcc
      language: cpp
      sudo: required
      dist: precise
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=gcc52_stdcpp14_sanitize
        - DETAILS=""
    - os: linux
      compiler: gcc
      language: cpp
      sudo: required
      dist: precise
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=ubuntu_1604
        - DETAILS=""
    - os: linux
      compiler: gcc
      language: cpp
      sudo: required
      dist: precise
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=precise_32bit
        - DETAILS=""
    - osx_image: xcode8
      language: objective-c
      compiler: clang
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=osx
        - DETAILS="debug build, libtool"

before_install:
  - ./gdal/ci/travis/${BUILD_NAME}/before_install.sh

install:
  - ./gdal/ci/travis/${BUILD_NAME}/install.sh

script:
  - ./gdal/ci/travis/${BUILD_NAME}/script.sh


